name: Flask CI

on: 
  push:
    branches: [main, master, feature/tests] #this means whenever we push into these branches its going to run the jobs below


jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2  
        with:
          python-version: 3.12
      
      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          python -m pytest tests/test_mock.py
          python -m pytest app_test.py

      # - name: Run tests unittest
      #   run: |
      #     python -m unittest discover -s tests -p 'test_*.py' #discover all files in tests directory with pattern of anything starts with test_ and ends with .py
      #     python app_test.py
      # - name: Run test on feature/tests branch
      #   run: python app_test.py
